### ISSUE TITLE
작업 환경 설정하기

### ISSUE THREAD

**Issue by kinesis19** [kinesis19/CygnusLauncher#1]
# Description
프로젝트 작업 환경을 설정한다.

# Tasks
- [x] repository clone 하기
- [x] Qt 프로젝트 생성하기
- [x] .gitignore 추가하기
- [x] Figma 프로젝트 생성하기

**Comment by kinesis19** [comment]
모든 Task를 완료하였기에 해당 Issue를 Close함.
